src/include: move ceph_to_hostos_errno() to separate header file
Including src/include/types.h in src/pybind/cephfs/types.pxd leads to
compilation error: "fatal error: acconfig.h: No such file or directory".
types.h as well as int_types.h include acconfig.h header file.

Move the code to be included in types.pxd to a separate file where
acconfig.h won't be included, thus preventing this error.

Signed-off-by: Rishabh Dave <ridave@redhat.com>